[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = ''
extend-exclude = '''
(
    \.git
    | migrations/  # 自動生成されたDB migrationファイル
)
'''

[tool.isort]
profile = "black"
skip_gitignore = true
extend_skip_glob = ["**/migrations/*"]  # 自動生成されたDB migrationファイル
