from logging import getLevelName

from core.config import get_settings

settings = get_settings()

bind = ["0.0.0.0:8000"]
# backlog=2048
workers = 1
worker_class = "uvicorn.workers.UvicornWorker"
# threads=1
worker_connections = 10000
# max_requests=0
max_requests_jitter = 500
# timeout=30
# graceful_timeout=30
# keepalive=2
# limit_request_line=4094
# limit_request_fields=100
# limit_request_field_size=8190
reload = True
# reload_engine=auto
# reload_extra_files=[]
# spew=False
# check_config=False
# print_config=False
# preload_app=False
# sendfile=None
# reuse_port=False
chdir = "/opt/app"
# daemon=False
# raw_env=[]
# pidfile=None
# worker_tmp_dir=None
# user=0
# group=0
# umask=0
# initgroups=False
# tmp_upload_dir=None
# secure_scheme_headers={'X-FORWARDED-PROTOCOL'='ssl', 'X-FORWARDED-PROTO'='https', 'X-FORWARDED-SSL'='on'}
# forwarded_allow_ips=['127.0.0.1']
accesslog = "-"
# disable_redirect_access_to_syslog=False
# access_log_format='%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
errorlog = "-"
loglevel = str(getLevelName(settings.LOG_LEVEL)).lower()
# capture_output=False
# logger_class=gunicorn.glogging.Logger
# logconfig=None
# logconfig_dict={}
# logconfig_json=None
# syslog_addr=udp://localhost:514
# syslog=False
# syslog_prefix=None
# syslog_facility=user
# enable_stdio_inheritance=False
# statsd_host=None
# dogstatsd_tags=
# statsd_prefix=
# pythonpath=None
# paste=None
# proxy_protocol=False
# proxy_allow_ips=['127.0.0.1']
# keyfile=None
# certfile=None
# ssl_version=2
# cert_reqs=0
# ca_certs=None
# suppress_ragged_eofs=True
# do_handshake_on_connect=False
# ciphers=None
# raw_paste_global_conf=[]
# strip_header_spaces=False
